name: Organization CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout ga_template repository
        uses: actions/checkout@v4

      # 3. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 5. Install dependencies with pip
      - name: Install dependencies with pip
        run: |
          pip install --upgrade pip mypy ruff

      # 6. Run Ruff for linting
      - name: Run Ruff for linting
        run: ruff check .

      # 7. Install Pyright
      - name: Install Pyright
        run: npm install -g pyright

      # 8. Run Pyright for type checking
      - name: Run Pyright for type checking
        run: pyright


      # 9. Run Mypy for type checking
      - name: Run Mypy for type checking
        run: mypy .
