name: Organization CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 呼び出し側リポジトリ（実際のコードがある側）をチェックアウト
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2. ga_template リポジトリから設定ファイルを blob 形式で取得
      - name: Fetch configuration files from ga_template
        run: |
          curl -sSL https://raw.githubusercontent.com/onga-team/ga_template/main/mypy.ini -o mypy.ini

      # 3. Python のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 4. Poetry のインストール
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with pip
        run: |
          pip install --upgrade pip
          pip install mypy

      # 6. 呼び出し側リポジトリ内の Python コードに対して Mypy を実行
      - name: Run Mypy for type checking
        run: poetry run mypy .

